name: server-ci
on: [push, pull_request]
jobs:
  import-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python -c "import importlib; importlib.import_module('src.main')"
